@echo off
echo Starting Social Media App...

echo Starting all services...
docker-compose up -d

echo Waiting for services to be ready...
timeout /t 5 /nobreak

echo Starting Go application...
go run cmd/server/main.go